src/offline_sorries.py
src/repl_api.py

Before this change REPL returned an error when the version of the lean project didn't match the most recent version of REPL. The version tag parameter allows users to specify the lean version that REPL uses that the version of the Lean project match the version of REPL.
Modify `src/repl_api.py` to checkout the REPL repo at this version.
The default is still the most recent version of REPL available.

feat: add --lean-version-tag parameter for offline sorrys

---

.gitignore

`offline_sorries` creates the lean_data directory when running in the repo root

fix: add lean_data to gitignore

---

src/sorryscraper/scripts/offline_sorries.py

`lake update` updates dependencies. This could cause a case where the sorry we are reproducing locally has a different set of dependencies from the remote.

fix: remove `lake update` step from offline_sorries.py

---

pyproject.toml
src/sorrydb/database/build_database.py
src/sorrydb/scripts/offline_sorries.py

Create new `database` package.
Move all functions other than `main` from offline_sorries.py to new build_database.py
Replace logic in offline_sorries `main` with new `build_database` function in build_database.py
Note, this is stacked on #11

refactor: move code to build_database to build_database.py

---

src/sorrydb/database/build_database.py
src/sorrydb/repro/repl_api.py
src/sorrydb/scripts/offline_sorries.py
tests/test_build_database.py

This PR makes several improvements to lean version handling:
- automatically detect the lean version of a repo (and remove the cli option)
- pull different versions of REPL for each lean version and store them in separate repos
- the metadata section of build_database results includes the lean version
Additionally I added a test which builds both the test repos to verify that two repos of different versions both produce sorries. This test fails on master.
Closes #13

Lean version handling

---

src/sorrydb/database/build_database.py

Simplifications to build_database.py in #18
introduced a minor bug which raises an exception
when a REPL finds no sorries in a specific file

fix: fix failure on no sorries in a specific lean file

---

src/sorrydb/database/build_database.py
src/sorrydb/scripts/build_sorry_db.py
src/sorrydb/scripts/offline_sorries.py

By default `build_database` now uses a temporary directory. 
The `--repos-file` flag remains to specify a non-temporary file. I think this option is useful for speeding up development.

feat: use tempfile for lean_data dir by default

---

src/sorrydb/database/build_database.py

This fixes a bug when running `update_db` on an existing sorry database.

fix: write to database with utc timezone

---

src/sorrydb/database/build_database.py

mathlib branches should get cached oleans a well (even though they do not have 'mathlib4' as dependency).

Cache for mathlib branches

---

src/sorrydb/database/build_database.py

Previously use "admit" and "proof_wanted" keywords as well as "sorry". However "admit" generates many false positives (common word in plain-English comments) and is deprecated, and "proof_wanted" is not technically a sorry (and not parsed as such by Lean).

Only use sorry keyword

---

src/sorrydb/crawler/git_ops.py

I also dropped the commit summary. I don't know what we would use this for, but I can add  it back if others disagree.
Closes #57

fix: remove blame author data from database

---

src/sorrydb/repl_client/__init__.py
src/sorrydb/repl_client/repl_client.py
src/sorrydb/scripts/client.py

This adds:
- `scripts/client.py` which takes a sorry json, reproduces it in repl, locates the correct proof_id, and (for now) just prints the proof state at that id
- `repl_client/repl_client.py` which implements the function of the script

feat: Repl client

---

repo_lists/active_repos_without_mathlib.json

Currently the [opencompl/mlir](https://github.com/opencompl/lean-mlir) (AKA opencompl/SSA. It must have been renamed.) repo takes a very long time to build compared to other repos and lake build eventually fails. I don't understand why exactly. It usually takes 2.5 hours to process this repo alone.
@LennyTaelman do you object to removing it from the active repos list for now? If lake build is always failing it isn't adding anything currently anyway. We can always add it back after we get the database up and running.

fix: remove SSA repo

---

pyproject.toml
sorrydb/cli/init_db.py
sorrydb/cli/run_rfl_client.py
sorrydb/cli/update_db.py
sorrydb/clients/rfl_client/rfl_client.py
sorrydb/database/build_database.py
sorrydb/database/process_sorries.py
tests/test_build_database.py
tests/test_git_ops.py

Poetry wasn't able to find the sub-directory packages.
This also avoids namespace collisions with other packages.

fix: use top-level sorrydb python package

---

sorrydb/database/build_database.py
sorrydb/database/sorry_database.py
tests/test_build_database.py

Add `new_leaf_commit`, `start_processing_time`, `end_processing_time`, `total_processing_time`, and `lake_timeout` to database stats at the repo level.
Stacked on #88

More database stats

---

sorrydb/utils/git_ops.py

Older versions of git format `refname:short` differently.
Switch to `refname` to support more versions of Git, specifically 2.39 which is used by default on Debian (and the python Docker image we use to deploy `sorrydb`).

fix: use `refname` instead of `refname:short` to format leaf commit refs

---

sorrydb/cli/run_rfl_client.py
sorrydb/clients/rfl_client/rfl_client.py
sorrydb/utils/repl_ops.py

This PR cleans up the rfl_client code:
- various fixes to imports
- split out the processing code in smalle sub-routines
- move `find_sorry_proof_state` to `LenRepl` method in `repl_ops`
- output {sorry, proof} dicts to json file
Does not yet harmonise this with `llm_client`, also not yet documented (should be part of major rewrite of `README.md`).

Rfl client cleanup

---

sorrydb/database/build_database.py
sorrydb/database/sorry_database.py

Using UTF-8 will make it easier to read and debug the SorryDB json output because the Unicode chars used in Lean goals will be visible instead of appearing as ASCII escapce sequences (`\uXXXXX`).

feat: encode Sorry database with UTF-8

---

sorrydb/agents/json_agent.py
sorrydb/agents/rfl_agent/__init__.py
sorrydb/database/build_database.py
sorrydb/database/process_sorries.py
sorrydb/utils/git_ops.py

`prepare_repository` and `remote_heads_hash` now raise errors in stead of returning `None`. Closes #122

git_ops error handling

---

sorrydb/cli/update_db.py
sorrydb/database/build_database.py
sorrydb/database/sorry_database.py
tests/test_json_database.py

Add human-readable markdown reports with aggregated statistics to sorrydb updates.
Add a `--report-file-path` option to `sorrydb update` command.
Here is a sample report:
- **Repositories with new commits:** 1
- **Repositories with lake timeout:** 0
- **Total sorries found:** 7
- **Total new goal sorries found:** 3
| Repository URL | Lake Timeout | Processing Time | Sorries | New Goal Sorries |
|----------------|--------------|-----------------|---------|------------------|
| https://github.com/austinletson/sorryClientTestRepo | No | 15s | 7 | 3 |
Closes #60

feat: improved database update stats and report

---

doc/DATABASE-SCRIPTS.md
sorrydb/cli/deduplicate_db.py
sorrydb/database/deduplicate_database.py
tests/mock_sorries.py
tests/test_deduplicate_database.py

This shouldn't be merged before feature freeze
This is useful for creating static benchmarks of `n` sorries

feat: add `--max-sorries` option to `deduplicate_db`

---

doc/Introduction_to_the_SorryDB_Project.ipynb
pyproject.toml
sorrydb/agents/json_agent.py
sorrydb/agents/llm_strategy.py
sorrydb/agents/rfl_strategy.py
sorrydb/cli/scrape_reservoir.py
sorrydb/database/reservoir.py
sorrydb/utils/repl_ops.py
sorrydb/utils/verify.py
tests/cli/test_settings.py
tests/test_build_database.py
tests/test_verify.py

Previously we only used a few rules.
Now that the codebase is growing, extend to the full default rule set.
Note, some rules may now require manual fixing,
i.e., they want be automatically fixed by `ruff check --fix`

chore: use ruff default linting configuration

---

sorrydb/utils/verify.py

On macOS, /var/folders/ is a symlink to /private/var/folders/. This caused path validation errors when computing relative paths between the repository directory and temporary files. Resolving both paths ensures consistent behavior across platforms.

fix: resolve symlinks in verify_proof for macOS compatibility
